# Generated by Django 3.1.4 on 2020-12-11 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('os', models.CharField(choices=[('ios', 'ios'), ('android', 'android')], max_length=7)),
                ('form_factor', models.CharField(choices=[('phone', 'phone'), ('tablet', 'tablet')], max_length=6)),
                ('model', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField()),
                ('enabled', models.BooleanField()),
            ],
        ),
    ]
